title: Education and Training
description: This is the documentation site for SSWR workshop.
url: "https://sail-ua.github.io/SSWR/"
remote_theme: https://github.com/JV-conseil/jekyll-theme-read-the-docs

# Sidebar navigation structure
nav:
  - title: "Home"
    url: "/"
    nav_order: 1
  - title: "Slides"
    url: "/slides"
    nav_order: 2
  - title: "Links to Datasets"
    url: "/datasets"
    nav_order: 3


