title: Education and Training
description: This is the documentation site for my project.
url: "https://sail-ua.github.io/no_code_ai.github.io/"
remote_theme: https://github.com/JV-conseil/jekyll-theme-read-the-docs

# Sidebar navigation structure
nav:
  - title: "Home"
    url: "/"
    nav_order: 1
  - title: "Slides"
    url: "/slides"
    nav_order: 2
  - title: "Flyer"
    url: "/flyer"
    nav_order: 3
  - title: "Links to Datasets"
    url: "/datasets"
    nav_order: 4
  - title: "Others"
    url: "/other"
    nav_order: 5

